TRUNCATE TABLE
  ai_usage_metrics,
  financial_metrics,
  stock_movements,
  inventory_items,
  order_print_jobs,
  order_items,
  orders,
  human_handoffs,
  messages,
  conversations,
  contacts,
  whatsapp_instances,
  knowledge_items,
  ai_agents,
  promotions,
  business_hours,
  product_addons,
  products,
  product_categories,
  business_profiles,
  subscriptions,
  users,
  companies
RESTART IDENTITY CASCADE;
